"""add 2fa fields to user

Revision ID: 805c4104f317
Revises: a4419b0d6fff
Create Date: 2026-08-02 10:03:13.958282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805c4104f317'
down_revision: Union[str, Sequence[str], None] = 'a4419b0d6fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('two_factor_code', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('two_factor_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'two_factor_expires_at')
    op.drop_column('refresh_tokens', 'two_factor_code')
    # ### end Alembic commands ###
