"""add failed_login_attempts and last_failed_login_at

Revision ID: ad963f979abf
Revises: d8c0bb441156
Create Date: 2026-08-02 08:52:57.285808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad963f979abf'
down_revision: Union[str, Sequence[str], None] = 'd8c0bb441156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login_at')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
