"""add 2fa fields to user

Revision ID: f4f56c78c2f6
Revises: ea49ddb3a35b
Create Date: 2026-08-02 10:30:00.805627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4f56c78c2f6'
down_revision: Union[str, Sequence[str], None] = 'ea49ddb3a35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'two_factor_expires_at')
    op.drop_column('refresh_tokens', 'two_factor_code')
    op.add_column('users', sa.Column('two_factor_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('two_factor_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_expires_at')
    op.drop_column('users', 'two_factor_code')
    op.add_column('refresh_tokens', sa.Column('two_factor_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('refresh_tokens', sa.Column('two_factor_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
